INSERT INTO user (user_id, name, job) VALUES (1, 'Sávio', 'Developer');
INSERT INTO user (user_id, name, job) VALUES (2, 'Leticia', 'Scrum Master');
INSERT INTO user (user_id, name, job) VALUES (3, 'Jeronimo', 'Analista');
INSERT INTO user (user_id, name, job) VALUES (4, 'Elthon', 'Analista');
INSERT INTO user (user_id, name, job) VALUES (5, 'Rebeca', 'Product Owner');
INSERT INTO user (user_id, name, job) VALUES (6, 'Lais', 'Triber Leader');
INSERT INTO user (user_id, name, job) VALUES (7, 'Thiago', 'Arquiteto');
INSERT INTO user (user_id, name, job) VALUES (8, 'Douglas', 'Analista');
INSERT INTO user (user_id, name, job) VALUES (9, 'João', 'Devops');
INSERT INTO user (user_id, name, job) VALUES (10, 'Angelo', 'DBA');
