INSERT INTO user (user_id, name, job, created_at) VALUES (1, 'Sávio', 'Developer', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (2, 'Leticia', 'Scrum Master', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (3, 'Jeronimo', 'Analista', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (4, 'Elthon', 'Analista', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (5, 'Rebeca', 'Product Owner', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (6, 'Lais', 'Triber Leader', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (7, 'Thiago', 'Arquiteto', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (8, 'Douglas', 'Analista', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (9, 'João', 'Devops', null);
INSERT INTO user (user_id, name, job, created_at) VALUES (10, 'Angelo', 'DBA', null);